### ISSUE TITLE
css virtualization 

### ISSUE THREAD

**Issue by nice-nickname** [nice-nickname/Incoding.Web.Components#62]
```css

.elem {
    overflow: auto;
    contain: content;
    will-change: transform;
    transform: translateZ(0);
    contain-intrinsic-size: auto none;
    will-change: scroll-position, contents;
}

```
